### ISSUE TITLE
[Feature Request] Call hierarchy support?

### ISSUE THREAD

**Issue by ofseed** [hedyhli/outline.nvim#50]
LSP supports call hierarchy, but such call hierarchy can only support one level. It would be great if a tree-like one could be implemented in the form of outline.nvim.

There's a plugin that supports this, [litee-calltree.nvim](https://github.com/ldelossa/litee-calltree.nvim).

I think the final form it tries to implement is like outline.nvim.

**Comment by hedyhli** [comment]
Thanks for the suggestion. However I don't envision having support for symbols other than ones defined in the current file to have built-in in outline.nvim, since it is currently out of scope.

It could be possible, however, to implement this as an [external provider](https://github.com/hedyhli/outline.nvim#external-providers) plugin, which will fetch the symbols from the call hierarchy, then make use of outline's API and interface to display it as a tree.

**Comment by adigitoleo** [comment]
Not clear if it is already supported or if it requires this call hierarchy business, but what I would really like to have is a list of only those symbols that are declared/defined in the current buffer. Maybe this is the wrong place to ask but I've looked and couldn't find much on that kind of filtering specifically.

**Comment by hedyhli** [comment]
Symbols come from the provider for a buffer, which could be LSP or CoC. In most cases these symbols should already be ones defined in the current buffer. Your request is unrelated to this issue.

@adigitoleo would you mind opening a new issue for this and include a screenshot, the programming language for the buffer and the contents of `:OutlineStatus` when the buffer in question is focused?

**Comment by adigitoleo** [comment]
Thanks, @hedyhli, I figured out that my expectations were incorrect. In Python, when I `import` something, then it will of course show up in the LSP listing for the current buffer, despite being "declared" elsewhere. So I think there is no issue.
